[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#925DF1"
red = "#ff7a93"
white = "#BBBED0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#8F919C"
yellow = "#e0af68"

[colors.primary]
background = "#1A1414"
foreground = "#cbd3f8"

[font]
size = 14

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Medium"

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.85
